{{- define "petclinic.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .serviceName }}
spec:
  selector:
    app: {{ .serviceName }}
  ports:
  - port: {{ .serviceConfig.port }}
    targetPort: {{ .serviceConfig.port }}
    name: http
{{- end -}}

# Generate services for all services
{{- range $serviceName, $serviceConfig := .Values.services }}
---
{{ template "petclinic.service" (dict "serviceName" $serviceName "serviceConfig" $serviceConfig "Release" $.Release) }}
{{- end }}

# Special case for tracing-server
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: tracing-server
spec:
  selector:
    app: tracing-server
  ports:
  - port: {{ .Values.tracing-server.port }}
    targetPort: {{ .Values.tracing-server.port }}
    name: http